### ISSUE TITLE
PreRelease ToDo: Output function

### ISSUE THREAD

**Issue by dakni** [ISAAKiel/mortAAR#9]
clean up the "ToDo's" in the code

rework examples and use the provided exemplary data

**Comment by nmueller18** [comment]
In the output tables I think the header should look like
`mortAAR` life table", grnam:class_of_deceased_str," (n = ",sum(x$Dx)," `individuals)"`,
formatted for example "mortAAR life table for sex:female (n = 53 individuals)".

**Comment by nmueller18** [comment]
In the plots I miss dx!
grnam should also be used for the legend instead of "dataset".
The captions of the plots are not correct, however, in the output-function they are. How is this possible?

**Comment by MartinHinz** [comment]
Fixed comment 2 with af172118c1394938012e30b851fd8c7fe0673eb5.
Regarding Comment 3, what do you mean with you miss dx?
Also, if you plot a life table list, the legend is correct, if it is a single life table, there is no grnam!?

**Comment by nmueller18** [comment]
Thanks for the fixes! Two more minor points:
1. Shouldn't it be "mortAAR"?
2. Instead of "Life expectation" I think "Life expectancy" is more common.

Is there a way to include the grouping column into the life tables (as suggested above)? Imagine the muensingen data grouped by the presence of absence of grave goods. The caption would then be, for example, "mortAAR life table for yes".

On the plots:
Forget my comment on dx!
I meant the caption of the legend in the plots and the captions of the plot themselves. Do these show up correctly when you play around with data?

**Comment by MartinHinz** [comment]
Granted, fixed 1 and 2.

Regarding grouping name, this should work already. Try out the following:
```{r}
library(mortAAR)
data("muensingen")
muensingen

library(stringi)
muensingen$age_beg <- stri_extract_first_regex(muensingen$age, "[0-9]+")
muensingen$age_beg <- as.numeric(muensingen$age_beg)
muensingen$age_end <- stri_extract_first_regex(muensingen$age, "-([0-9]+)$")
muensingen$age_end <- substr(muensingen$age_end,2,length(muensingen$age_end))
muensingen$age_end[3] <- muensingen$age_beg[3]
muensingen$age_end <- as.numeric(muensingen$age_end)

munsingen.prep <- prep.life.table(muensingen, agebeg = "age_beg", ageend = "age_end", grnam = "grave_goods")

life.table(munsingen.prep)
```

Should give you the desired result.

Having this, you also might to check if the plots are now correct (sorry, copy-paste error before)...

```{r}
plot(life.table(munsingen.prep))
```

**Comment by nmueller18** [comment]
Life table: Better now. However, there is still the column "Age" from `life.table.prep` printed.

Plot: Still not correct.
1. no dx-plot, lx would be nice, too.
2. The general legend is partly incorrect:
dx: proportion of deaths
qx: probability of death
lx: survivorship
3. Legend caption "dataset" instead of grouping variable.

**Comment by nevrome** [comment]
Oh... I obviously misunderstood [this](https://github.com/ISAAKiel/mortAAR/issues/20#issuecomment-307769808) comment. `life.table()` does indeed "ignore" the "Age"-column: It doesn't do anything with it but pipes it forward to the result. That's not what you wanted, obviously... Annoying.

**Comment by MartinHinz** [comment]
OK, solved 1 and 2 of Nils comment (see commits de893723ce135b325b1666cc3357df337badab06, 3160d13cae7c3dfb6924a6c2883560efdc0626a1, 52d11807f54c4b5789e0e554ce05de9c907fae75 and 7cd5085d2c3cd777333628ba5b8082a2f108097d).

3 is a problem: the information of the grouping variable is not available in the final life table object. @nevrome, do you think it would be worthwhile and feasible to store the information of the grouping variable in the final life table object, eg. as lt$grname?

**Comment by nevrome** [comment]
@MartinHinz Wait... where did my comment go? Maybe I forgot to click the submit button the first time? 

Anyway: 
```
lt <- schleswig_ma[c("a", "Dx")] %>% life.table()
attr(lt,'grname') <- 'bohrmaschine'
attributes(lt) 
```
Are attributes a possible solution for the problem?

**Comment by MartinHinz** [comment]
Perfect, looking forward to you implementing it!

**Comment by nevrome** [comment]
Puhh... We will have to drag it through the whole package. But this shouldn't be too complicated. I volunteer as tribute :raised_hand:!

**Comment by MartinHinz** [comment]
@nmueller18 , is it as important in from your perspective that it would justify this effort?

**Comment by nmueller18** [comment]
I cannot really estimate how much effort it is. An attribute would certainly be useful, on the one hand for the plots (which otherwise you would definitely have to adjust with something like Illustrator), but also for the life tables themselves (for implementing something like "grnam: option1/2/3 etc.", e.g. "Gender: female").
The attribute could be `grnam`, and if that is not given the file name.

**Comment by nevrome** [comment]
I created [this branch](https://github.com/ISAAKiel/mortAAR/commits/legend_of_conan) to deal with the problem. It's ridiculously complicated in relation to the effect, but now we're going to do this.

@MartinHinz The prep.life.table() tests fail now naturally. Please fix and/or provide the script that produces the prep_output dataset. I was not able to find it. 

Honest question: Why does the output need so much boilerplate code? Isn't there a possibility to generalize this?

**Comment by MartinHinz** [comment]
prep.life.table is now tested against specific characteristics of the output, no hard code example dataset necessary anymore. You might mirror it into the development branch.

**Comment by MartinHinz** [comment]
Regarding your question: This technique is a very well developed programming pattern. It is called [CPP](https://en.wikipedia.org/wiki/Copy_and_paste_programming).

But if you really insist, you aesthete, I might [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) it.

**Comment by nevrome** [comment]
For a second I was confused and curious, which mighty and powerful programming technique I'm going to learn by following your CPP link... :-)

If you have time, please shorten it for the sake of readability and possible future additions. Otherwise open a post release issue.

**Comment by MartinHinz** [comment]
That was the intention!

The real reason was to keep the code simple straight forward to make it more readable. Currently I am juggling around with meta programming, will make the thing much more dry, but harder to understand. Watch this space.

**Comment by nevrome** [comment]
I'm very excited!

**Comment by MartinHinz** [comment]
And rightly so. First drying in 40982363dc037df84ec93cab09eafb43a0613df0. More to come.

**Comment by nmueller18** [comment]
I just noticed that the x-axis is labelled in hundreds.

**Comment by nevrome** [comment]
@MartinHinz @dakni The prophet is working on a [new way](https://www.rstudio.com/resources/webinars/whats-new-in-dplyr-0-7-0/?wvideo=qmeobayghd&wtime=1492) of Metaprogramming in the tidyvers. FYI.

**Comment by MartinHinz** [comment]
You mean the y-axis in the probability based plots? That is because the values in the processed life tables are percent, so it is labeled in the interval [0-100].

Possible solutions:

1. Live with that
2. Rescale to [0,1]
3. Change the analytical function so that its output is in [0-1]

I opt for 1.

If you really mean x-axis, I can not reproduce that, please specify and give a code example.

Otherwise, I think this issue is close to being closed, isn't it?

**Comment by nmueller18** [comment]
Sorry to have been unclear. Y-axis is okay, it is really the x-axis. Please have a look at the Magdalenenberg-output in the vignette (Muesingen output is okay).

**Comment by MartinHinz** [comment]
Thanks, my fault. Should be solved with b8198a6d2b81918cacfbf32f72b03c70bc507521, please check and close issue if you are satisfied.
